//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Client
    {
        public TS_Client()
        {
            this.TS_HoursDay = new HashSet<TS_HoursDay>();
            this.TS_Project = new HashSet<TS_Project>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public Nullable<int> KmToOffice { get; set; }
        public Nullable<bool> AppOwner { get; set; }
    
        public virtual ICollection<TS_HoursDay> TS_HoursDay { get; set; }
        public virtual ICollection<TS_Project> TS_Project { get; set; }
    }
}
