//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_HoursKind
    {
        public TS_HoursKind()
        {
            this.TS_HoursDay = new HashSet<TS_HoursDay>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TS_HoursDay> TS_HoursDay { get; set; }
    }
}
