//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Project
    {
        public TS_Project()
        {
            this.TS_UserProject = new HashSet<TS_UserProject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Client { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual TS_Client TS_Client { get; set; }
        public virtual ICollection<TS_UserProject> TS_UserProject { get; set; }
    }
}
